apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webflux-cassandra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/lucasGalo/webflux-cassandra.git'
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
